ARG DOCKER_REGISTRY=docker.io
ARG FROM_IMG_REPO=qspack
ARG FROM_IMG_NAME="centos-cmake"
ARG FROM_IMG_TAG="2019-04-17"
ARG FROM_IMG_HASH=""
FROM ${DOCKER_REGISTRY}/${FROM_IMG_REPO}/${FROM_IMG_NAME}:${FROM_IMG_TAG}${DOCKER_IMG_HASH}

RUN spack graph py-lit@0.5.0 \
 && spack install py-lit@0.5.0
